name: operations
recipe: drupal9
config:
  webroot: web
  php: '8.1'
  drush: ^10
  xdebug: 'develop,debug'

  # See https://github.com/lando/lando/issues/2948#issuecomment-1003484299
  database: mysql:8.0
  config:
    database: /dev/null

proxy:
  appserver:
    - operations.lndo.site
#
#  mercury_web:
#    - mercury.lndo.site
#
#  mars_web:
#    - mars.lndo.site

  venus_web:
    - venus.lndo.site
    - mars.lndo.site
    - mercury.lndo.site

services:
  appserver:
    build:
      - 'export PATH="/var/www/.composer/vendor/bin"'
      - 'composer install'
    xdebug: true
#    overrides:
#      environment:
#        DRUSH_OPTIONS_URI: "https://ox.lndo.site"
#
  mercury_web:
    type: php:8.1
    webroot: web
    xdebug: true

  mars_web:
    type: php:8.1
    webroot: web
    xdebug: true

  venus_web:
    type: php:8.1
    webroot: web
    xdebug: true
#
#  operations:
#    type: mysql:8.0
#    portforward: 33067
##    config:
##      confd: lando/mysql/conf.d
#
  operations:
    type: mysql:8.0
    portforward: 33067

  mercury:
    type: mysql:8.0
    portforward: 33068
#    config:
#      confd: lando/mysql/conf.d

  venus:
    type: mysql:8.0
    portforward: 33069
#    config:
#      confd: .lando/mysql/conf.d

  mars:
    type: mysql:8.0
    portforward: 33070
#    config:
#      confd: .lando/mysql/conf.d
#

tooling:
  sync:
    service: appserver
    cmd: "drush sql:sync --extra-dump=--single-transaction=false @live @self"
  phpcs:
    service: appserver
    cmd: "phpcs"
    options:
    description: Run phpcs for given folder or file.
  drupal-check:
    service: appserver
    cmd: "drupal-check"
    options:
    description: Run drupal-check for given folder or file.
  twig-lint:
    service: appserver
    cmd: "php /var/www/twig-lint.phar"
    options:
    description: Run twig-lint for given folder or file.
  eslint:
    service: node
    cmd: "node ./node_modules/eslint/bin/eslint.js --config=.eslintrc.json"
    options:
    description: Run jshint for given folder or file.
  stylelint:
    service: node
    cmd: "npx stylelint --config=.stylelintrc.json"
    options:
    description: Run stylelint for given folder or file.
  drush:
    service: appserver
