field.formatter.settings.site_state:
  type: mapping
  label: State formatter settings
  mapping:
    show_reason:
      type: string
      label: Show reasons

    reason_collapsible:
      type: string
      label: Collapsible fieldset

    reason_open:
      type: string
      label: Fieldset is open or closed.