task.task_type.*:
  type: config_entity
  label: 'Task type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

    command_template:
      type: string
      label: 'Command Template'
      description: 'The command to run, optionally using tokens to create a command from field data.'
