# Schema for the configuration files of the DevShop Tasks module.
devshop_task.settings:
  type: config_object
  label: 'DevShop Tasks settings'
  mapping:
    example:
      type: string
      label: 'Example'
